# syntax=docker/dockerfile:1
# Generated by Coolpack
# Provider: node, Framework: nextjs, Output: server

FROM node:22-alpine AS builder
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json* ./

RUN npm install --legacy-peer-deps

COPY . .

# Disable Next.js telemetry during build
ENV NEXT_TELEMETRY_DISABLED=1

RUN npm run build

FROM node:22-alpine AS runner
WORKDIR /app

RUN addgroup --system --gid 1001 coolgroup && \
    adduser --system --uid 1001 --ingroup coolgroup cooluser

ENV NODE_ENV=production

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/package.json ./

RUN chown -R cooluser:coolgroup /app
USER cooluser

EXPOSE 3020

CMD ["npm", "run", "start"]
